### ISSUE TITLE
link to demo in readme is broken

### ISSUE THREAD

**Issue by nwpointer** [plasmicapp/nextjs-starter-plv1#1]
<img width="995" alt="Screen Shot 2021-02-27 at 6 55 24 PM" src="https://user-images.githubusercontent.com/3927051/109406384-5c106680-792d-11eb-8a7e-a48fd625ea33.png">

**Comment by yang** [comment]
Thanks for reporting, will fix!

**Comment by ryscheng** [comment]
Fixed. Thanks for pointing it out!
